# Generated by Django 4.1.7 on 2026-04-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
