# Generated by Django 4.1.7 on 2026-04-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_sku_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_notified',
            field=models.BooleanField(default=False),
        ),
    ]
