# Generated by Django 4.1.7 on 2026-04-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_low_stock_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retail_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
