# Generated by Django 4.2.30 on 2026-05-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_purchaseorder_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
