# Generated by Django 4.2.30 on 2026-05-06 16:22

from django.db import migrations
from django.contrib.auth.models import User


def assign_first_user(apps, schema_editor):
    first_user = User.objects.first()
    if first_user:
        Category = apps.get_model('inventory', 'Category')
        Product = apps.get_model('inventory', 'Product')
        Expense = apps.get_model('inventory', 'Expense')
        DebtAccount = apps.get_model('inventory', 'DebtAccount')
        FinanceTransaction = apps.get_model('inventory', 'FinanceTransaction')
        MonthlyBudget = apps.get_model('inventory', 'MonthlyBudget')
        PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')

        Category.objects.filter(user__isnull=True).update(user=first_user)
        Product.objects.filter(user__isnull=True).update(user=first_user)
        Expense.objects.filter(user__isnull=True).update(user=first_user)
        DebtAccount.objects.filter(user__isnull=True).update(user=first_user)
        FinanceTransaction.objects.filter(user__isnull=True).update(user=first_user)
        MonthlyBudget.objects.filter(user__isnull=True).update(user=first_user)
        PurchaseOrder.objects.filter(user__isnull=True).update(user=first_user)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_category_user_debtaccount_user_expense_user_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_first_user, reverse),
    ]
