# Generated by Django 4.2.30 on 2026-05-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_activitylog_product_display_order'),
        ('inventory', '0013_assign_user_to_existing_data'),
    ]

    operations = [
    ]
